// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT1klw_vG_Mc4T2RpONKbqi6XolyKY6A0',
    appId: '1:981540824786:web:6a1935335e4f41e6c52f0b',
    messagingSenderId: '981540824786',
    projectId: 'learning-app-8bdb7',
    authDomain: 'learning-app-8bdb7.firebaseapp.com',
    storageBucket: 'learning-app-8bdb7.firebasestorage.app',
    measurementId: 'G-57DYRPF9DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcusVZhM0u4unexOjfDfTT9VJp4atG19c',
    appId: '1:981540824786:android:2c35a0e4e5ab0ccec52f0b',
    messagingSenderId: '981540824786',
    projectId: 'learning-app-8bdb7',
    storageBucket: 'learning-app-8bdb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBApInHVsO27scAq1T1MX-x_XlexvSp5Ck',
    appId: '1:981540824786:ios:ef8caa775a04c93dc52f0b',
    messagingSenderId: '981540824786',
    projectId: 'learning-app-8bdb7',
    storageBucket: 'learning-app-8bdb7.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBApInHVsO27scAq1T1MX-x_XlexvSp5Ck',
    appId: '1:981540824786:ios:ef8caa775a04c93dc52f0b',
    messagingSenderId: '981540824786',
    projectId: 'learning-app-8bdb7',
    storageBucket: 'learning-app-8bdb7.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT1klw_vG_Mc4T2RpONKbqi6XolyKY6A0',
    appId: '1:981540824786:web:bd1fc5d9d06b7ac0c52f0b',
    messagingSenderId: '981540824786',
    projectId: 'learning-app-8bdb7',
    authDomain: 'learning-app-8bdb7.firebaseapp.com',
    storageBucket: 'learning-app-8bdb7.firebasestorage.app',
    measurementId: 'G-PKG92F13LH',
  );
}
